version: "3.9"

services:
  backend:
    build: .
    container_name: bloodbank-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/lifestream
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=90d
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USERNAME=your-email@gmail.com
      - EMAIL_PASSWORD=your-email-password
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: bloodbank-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
