version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile   # ✅ since your Dockerfile is in the root
    container_name: bloodbank-backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: bloodbank-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bloodbank
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
