services:
  backend:
    build:
      context: ./backend   # <-- point to the folder containing package.json
    container_name: bloodbank-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://db:27017/bloodbank
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: bloodbank-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
