name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for package.json
        id: check_pkg
        run: |
          if [ -f package.json ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js (only if package.json exists)
        if: ${{ steps.check_pkg.outputs.exists == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (only if package.json exists)
        if: ${{ steps.check_pkg.outputs.exists == 'true' }}
        run: npm ci

      - name: Build (only if package.json exists)
        if: ${{ steps.check_pkg.outputs.exists == 'true' }}
        run: npm run build --if-present

      - name: Show repo files & status
        run: |
          echo "package.json present: ${{ steps.check_pkg.outputs.exists }}"
          ls -la
          echo "✅ CI job finished"
